# Generated by Django 5.1.4 on 2025-01-24 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_id', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Private Room', 'Private Room')], max_length=20)),
                ('status', models.CharField(choices=[('Empty', 'Empty'), ('Occupied', 'Occupied')], default='Empty', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
