# Generated by Django 5.1.4 on 2025-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_bed_hospital_rename_user_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Events', 'Events'), ('Alerts', 'Alerts')], default='Health', max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
