# Generated by Django 5.1.4 on 2025-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_communityupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Psychologist', 'Psychologist')], max_length=50)),
                ('contact_info', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('availability', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='healthcare_profiles/')),
            ],
        ),
    ]
