# Generated by Django 5.1.4 on 2025-01-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_healthcareprofessional'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('General Health', 'General Health'), ('Fitness', 'Fitness'), ('Diet', 'Diet'), ('Mental Health', 'Mental Health'), ('Diseases', 'Diseases')], max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medinfo_images/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
