# Generated by Django 5.1.4 on 2025-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_medicalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Supplies', 'Supplies')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
