# Generated by Django 5.1.4 on 2025-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='MedicalInventory',
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='category',
            field=models.CharField(choices=[('General Health', 'General Health'), ('Fitness', 'Fitness'), ('Diet', 'Diet'), ('Mental Health', 'Mental Health'), ('Diseases', 'Diseases'), ('Medicine', 'Medicine'), ('Equipment', 'Equipment')], max_length=50),
        ),
    ]
