# Generated by Django 5.1.4 on 2025-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
